
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/ssl/olympus-selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/olympus-selfsigned.key;

    location ~ ^/(gods|creatures|myths) {
        proxy_cache olympus_cache;
        proxy_cache_valid 200 30s;
        add_header X-Cache-Status $upstream_cache_status;
        add_header X-Upstream-Addr $upstream_addr always;
        proxy_pass http://olympus_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        add_header X-Upstream-Addr $upstream_addr always;
        proxy_pass http://olympus_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
